# Generated by Django 6.0 on 2026-02-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_order_address_order_email_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bank', 'Bank Transfer'), ('momo', 'Momo'), ('vnpay', 'VNPay'), ('stripe', 'Stripe')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
