# Generated by Django 6.0 on 2026-03-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_order_shipping_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_company',
        ),
    ]
