# Generated by Django 6.0 on 2026-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_returnrequest_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
